### ISSUE TITLE
Grocy API through Traefik

### ISSUE THREAD

**Issue by powerdude** [PantryParty/pantry_party#94]
hello,

I'm exposing grocy through traefik and having an issue using this app.  Here's my traefik config:
```yaml
services:
  grocy:
    image: linuxserver/grocy
    container_name: grocy
    environment:
      - PUID
      - PGID
      - TZ
    volumes:
      - ${CONFIG_DIR}/grocy/data:/config
      - "/etc/localtime:/etc/localtime:ro"
    ports:
      - 9283:80
      - 9284:443
    restart: unless-stopped
    networks:
      - t2_proxy  
    labels:
      - "traefik.enable=true"
      ## HTTP Routers Auth Bypass
      - "traefik.http.routers.grocy-rtr-bypass.entrypoints=http,https"
      - "traefik.http.routers.grocy-rtr-bypass.rule=Headers(`GROCY-API-KEY`, `$GROCY_API_KEY`) || Query(`GROCY-API-KEY`, `$GROCY_API_KEY`)"
      #- "traefik.http.routers.grocy-rtr-bypass.tls=true"
      - "traefik.http.routers.grocy-rtr-bypass.priority=100"
      ## HTTP Routers Auth
      #- "traefik.http.routers.grocy-rtr.entrypoints=https"
      - "traefik.http.routers.grocy-rtr.rule=Host(`grocy.$DOMAINNAME`)"
      - "traefik.http.routers.grocy-rtr.tls=true"
      - "traefik.http.routers.grocy-rtr.priority=99"
      ## Middlewares
      - "traefik.http.routers.grocy-rtr-bypass.middlewares=chain-no-auth@file"
      - "traefik.http.routers.grocy-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.grocy-rtr.service=grocy-svc"
      - "traefik.http.routers.grocy-rtr-bypass.service=grocy-svc"
      - "traefik.http.services.grocy-svc.loadbalancer.server.port=80"
```

the error i get from the app is:
An unknown error occurred. Got HTTP status code 200.

isn't 200 a success code?
